### ISSUE TITLE
packge version conflicts 

### ISSUE THREAD

**Issue by siminLi97** [AIBreeding/DNNGP#10]
Dear Professor,

I have encountered some issues with the following package versions:

- tensorflow=2.6.0
- scikit-learn=1.2.1
- numpy=1.23.5
- pandas=1.5.2
- keras=2.6.0

It seems that there are version conflicts between these packages when running in an environment with Python version 3.9.16. I am facing compatibility issues that prevent normal operation.

Could you please advise on a recommended solution or a compatible set of versions to resolve these compatibility issues? Thank you very much for your assistance!

Best regards！
lunpingliang

**Comment by z4668640** [comment]
Perhaps you can experiment with several dependent versions, as long as it is python3.9 environment, the control of the dependency version does not need to be completely consistent.

**Comment by chaimol** [comment]
the tensorflow=2.6.0 is require numpy~=1.19.5.this is a conflict. Can you tell me which package version should be modified? Is it tensorflow or numpy?

**Comment by z4668640** [comment]
> the tensorflow=2.6.0 is require numpy~=1.19.5.this is a conflict. Can you tell me which package version should be modified? Is it tensorflow or numpy?

You can try the updated yaml file now. On my machine, an environment configured directly with conda's yaml file can be used directly.

**Comment by chaimol** [comment]
> > the tensorflow=2.6.0 is require numpy~=1.19.5.this is a conflict. Can you tell me which package version should be modified? Is it tensorflow or numpy?
> 
> You can try the updated yaml file now. On my machine, an environment configured directly with conda's yaml file can be used directly.

yes, use `conda install --yes --file requirements.txt` can auto solve the confict. Do not use pip install the requirements.

**Comment by z4668640** [comment]
> > > the tensorflow=2.6.0 is require numpy~=1.19.5.this is a conflict. Can you tell me which package version should be modified? Is it tensorflow or numpy?
> > 
> > 
> > You can try the updated yaml file now. On my machine, an environment configured directly with conda's yaml file can be used directly.
> 
> yes, use `conda install --yes --file requirements.txt` can auto solve the confict. Do not use pip install the requirements.

In fact, I recommend using yaml files to create conda environments, like this: `conda env create -f environment.yml -n myenv`.
In this mode, both `conda install` and `pip install` can be used.
