### ISSUE TITLE
https://github.com/AIBreeding/DNNGP/blob/main/example-data.tgz file are missing

### ISSUE THREAD

**Issue by chaimol** [AIBreeding/DNNGP#7]
I am readling your paper "DNNGP, a deep neural network-based method for genomic prediction using multi-omics data in plants" in MP. Your writing the the research data put in "https://github.com/AIBreeding/DNNGP/blob/main/example-data.tgz". but i cannot find this file. maybe this file is too big for github.
# Can you provide another download link?

**Comment by z4668640** [comment]
Same as #11
