### ISSUE TITLE
PCA issues

### ISSUE THREAD

**Issue by daybreak0807** [AIBreeding/DNNGP#8]
I saw in your document that you mentioned using PLINK for PCA dimensionality reduction, but I see that almost all genomes have feature vector values within ± 1 after using PLINK dimensionality reduction. Why is your data value range within ± 100? Is there any other dimensionality reduction method used?

**Comment by z4668640** [comment]
Hello, I guess the difference in values after PCA should be related to the data itself. In addition, I checked the data after PCA and found no ±1.
In addition, the model supports any two-dimensional table with numeric data, in other words you can try any dimensionality reduction you are comfortable with, but PCA is more common for most people.

**Comment by yunmika** [comment]
Hello, to perform PCA on SNP, do we need to calculate the G matrix first and then perform PCA on the G matrix? Is there any other way to perform PCA directly on the SNP matrix? I know very little about this, and I hope the author can help answer this question. Thank you！

**Comment by z4668640** [comment]
> Hello, to perform PCA on SNP, do we need to calculate the G matrix first and then perform PCA on the G matrix? Is there any other way to perform PCA directly on the SNP matrix? I know very little about this, and I hope the author can help answer this question. Thank you！

You can use plink software to PCA SNP data files directly. Plink software supports a variety of data formats and can handle many situations, so it is recommended to try it out.

**Comment by yunmika** [comment]
OK, thank you

> > 你好，做SNP的PCA是不是要先算出G矩阵，再对G矩阵做PCA？还有没有其他方法可以直接对SNP矩阵做PCA？我了解的很少，希望作者能帮忙解答一下，谢谢！
> 
> 可以直接使用plink软件对SNP数据文件进行PCA分析，plink软件支持多种数据格式，可以处理多种情况，建议尝试一下。

**Comment by yunmika** [comment]
> > Hello, to perform PCA on SNP, do we need to calculate the G matrix first and then perform PCA on the G matrix? Is there any other way to perform PCA directly on the SNP matrix? I know very little about this, and I hope the author can help answer this question. Thank you！
> 
> You can use plink software to PCA SNP data files directly. Plink software supports a variety of data formats and can handle many situations, so it is recommended to try it out.

OK, thank you
