### ISSUE TITLE
cannot find modules

### ISSUE THREAD

**Issue by Cauwth** [AIBreeding/DNNGP#9]
![image](https://github.com/AIBreeding/DNNGP/assets/143175589/06e5b2cc-00a5-4335-adb8-2d3f37da99fc)
When I run the sample code, the following error occurs. How should I deal with it? I have already installed the relevant dependencies, and here is my `script` directory
![image](https://github.com/AIBreeding/DNNGP/assets/143175589/f1daa062-6d71-4a26-8a4f-05aaba755dc1)

**Comment by z4668640** [comment]
I think you need this: https://github.com/AIBreeding/DNNGP/blob/main/Scripts/config_dnngp.cp39-win_amd64.pyd
